controller_list:
  - name: abb_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - abb2_joint_1
      - abb2_joint_2
      - abb2_joint_3
      - abb2_joint_4
      - abb2_joint_5
      - abb2_joint_6
  - name: barrett_hand_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger_1_prox_joint
      - finger_1_med_joint
      - finger_2_prox_joint
      - finger_2_med_joint
      - finger_3_med_joint